name: base 
channels:
  - conda-forge
dependencies:
  - altair
  - duckdb-engine
  - gh-scoped-creds
  - glances
  - git-filter-repo
  - ibis-duckdb
  - jupyter-resource-usage
  - jupyter-rsession-proxy
  - jupyter-vscode-proxy
  - jupyterhub-singleuser
  - jupyterlab-git
  - pip
  - plotnine
  - pypdf
  - pip:
    - jupyter-tensorboard-proxy
    - jupyter-keepalive

