name: base 
channels:
  - conda-forge
dependencies:
  - boto3
  - cartopy
  - distributed
  - earthaccess
  - exactextract
  - fiona
  - fsspec
  - gcsfs
  - gdal
  - geoarrow-types
  - geopandas
  - geocube
  - h5netcdf
  - icechunk
  - jupytergis
  - leafmap
  - libgdal-arrow-parquet
  - localtileserver
  - mapclassify
  - maplibre
  - minio
  - netCDF4
  - odc-geo
  - odc-stac
  - planetary-computer
  - pmtiles
  - polars
  - pyarrow
  - pydeck
  - pyogrio
  - pystac
  - pystac-client
  - rasterio
  - rasterstats
  - requests
  - rio-cogeo
  - rioxarray
  - stackstac
  - streamlit
  - tippecanoe
  - tqdm
  - xarray
  - zarr
  - pip
  - pip:
    - pcodec


