name: ARM64 Image
on:
  workflow_dispatch: null
  push:
    paths: 
      - Dockerfile.arm
      - environment.yml
      - install_arm.r
      - install_r.sh
      - install_rstudio.sh
      - install_utilities.sh
      - vscode-extensions.txt
      - Rprofile
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: free extra disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h
      - uses: actions/checkout@v3
      - name: Set up QEMU (arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker-org/cuda
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile.arm
          platforms: linux/arm64
          tags: arm64
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker/cuda
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
          dockerfile: Dockerfile.arm
          platforms: linux/arm64
          tags: arm64

