name: ARM64 pre-build base
on:
  workflow_dispatch: null
  push:
    paths: 
      - Dockerfile.arm.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: free extra disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h
      - uses: actions/checkout@v3
      - name: Set up QEMU (arm64)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Publish to GitHub Container Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: rocker-org/rapids-base
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile.arm.1
          platforms: linux/arm64
          tags: arm64

