name: Build CUDA (GPU) Base

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC
  push:
    paths:
      - Dockerfile.cuda
      - install*.sh
      - Rprofile
      - vscode-extensions.txt
      - requirements.cuda.txt
      - .github/workflows/build-cuda.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push CUDA Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.cuda
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rocker-org/cuda:latest
            ghcr.io/rocker-org/cuda:cuda13.0-py3.12-rapids25.12
            ghcr.io/rocker-org/cuda:cuda13.0-py3.12
            ghcr.io/rocker-org/cuda:cuda13.0
            rocker/cuda:latest
            rocker/cuda:cuda13.0-py3.12-rapids25.12
            rocker/cuda:cuda13.0-py3.12
            rocker/cuda:cuda13.0
          build-args: |
            NB_USER=jovyan
