name: Build CUDA-Spatial (GPU)

on:
  workflow_dispatch:
  push:
    branches: [master,main]
    paths:
      - 'extend/Dockerfile.cuda'
      - 'extend/requirements.cuda.txt'
      - 'extend/install.r'
  pull_request:
    paths:
      - 'extend/Dockerfile.cuda'
      - 'extend/requirements.cuda.txt'
      - 'extend/install.r'
  workflow_run:
    workflows: ["Build CUDA (GPU) Base"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push CUDA-Spatial
        uses: docker/build-push-action@v4
        with:
          context: extend
          file: extend/Dockerfile.cuda
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rocker-org/cuda-spatial:latest
            rocker/cuda-spatial:latest
          build-args: |
            BASE=rocker/cuda:latest
